import Head from 'next/head'
import Image from 'next/image'
import ContainerFour from '../components/ContainerFour'
import ContainerOne from '../components/ContainerOne'
import ContainerThree from '../components/ContainerThree'
import ContainerTwo from '../components/ContainerTwo'
import Newsletter from '../components/Newsletter'
import Questions from '../components/Questions'

import styles from '../styles/Home.module.css'

//This gets rendered on the Client Side
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hulu with Next.JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContainerOne />
      <ContainerTwo />
      <ContainerThree />
      <ContainerFour />
      <Questions />
      <Newsletter />
    </div>
  )
}